/*global CryptoJS, angular*/
var requestModule = angular.module("settingsModule", []);

requestModule.factory("SettingsService", function ($http, config) {
    "use strict";
    /************************************************/
    /** General functions                          **/
    /************************************************/
    var theServiceObject = {};

    theServiceObject.helloWorld = function (successCallback) {

        //$http.post(config.backend + "/api/v1/apiconsole/user/validateUser", { email: email, password: hashedPassword })
        //    .success(function (data) {
        //        if (data.data === null) {
        //            successCallback(null);
        //        } else {
        //            successCallback(data);
        //        }
        //    })
        //    .error(function (data, status) {
        //        console.error("AJAX ERROR:", "login:", status, data);
        //    });

        //$http.get(config.backend + "/api/v1/apiconsole/assertionGroups/history/user")
        //    .success(function (data) {
        //        callback(data);
        //    })
        //    .error(function (data) {
        //        errCallback(data);
        //    });

        successCallback("This text was generated by an Angular-service!");
    };

    theServiceObject.getSetting = function (setting, callback) {

        $http.get(config.backend + "settings/" + setting)
            .success(function (data) {
                if(data.error) {
                    callback("Site name");
                }  else {
                    callback(data.setting);
                }
            })
            .error(function (data) {
                callback(null);
            });
    };

    theServiceObject.getSettings = function (callback) {

        $http.get(config.backend + "settings")
            .success(function (data) {
                callback(data.settings);
            })
            .error(function (data) {
                callback(null);
            });
    };

    return theServiceObject;
});